version: '3'
services:
    front-server:
      build: 
        context: .
        dockerfile: Dockerfile.dev
      ports: 
        - "3001:3000"
      volumes:
        - /app/node_modules
        - .:/app
    
    test:
      build: 
        context: .
        dockerfile: Dockerfile.dev    
      volumes:
        - /app/node_modules
        - .:/app
      command : ["npm","run","test"]
      
    production:
      build: .
      ports: 
        - "3000:3000"
        

